language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  
  addons:
  sonarcloud:
    organization: "djon-wick_laba1"
    token:
secure: $SONAR_TOKEN

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"

notifications:
  email: false
